### ISSUE TITLE
Summary of review 26.4.

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#1176]
Refers to staging version:
https://github.com/CSCfi/rems/commits/95cd1d311ad209aa5fce3f83eb4cd04fcbd98822

# Positive feedback
- Tero and I decided that the new colour scheme just fine for now (unlike reported by Tero earlier)
- the UI is fast and snappy.

# UI issues
- [x] #1128 capitalize menu (e.g. "CATALOGUE") and hilight active menu as in production lbr.csc.fi  
- [x] #1133 application numbering: still important to us (was not promised for this rc) 
- ~~"..." in most buttons should be removed~~
- [x] #472 #1231 About > Privacy Policy (see production lbr.csc.fi)
- [x] #1186 UI logic problem: User cannot retract saved application or get out of application if she does not want to accept terms.  
- [x] #1179 Catalog items: Rightmost buttons chopped in FF ( as reported by Tero, tested on latest ESR in Linux);  (works ok in Chromium). 
- [x] https://github.com/CSCfi/rems/issues/1275

# Bugs
- [x] #1199 Bug: Request decision without specified deciders:
Request decision
Failed
Missing translation [:deciders]Missing translation [:must-not-be-empty]

- [x] #1191 Bug: https://lbr.csc.fi/#/application/809
shows up under "Open applications" after approval
Expected: Under processed applications

**Comment by luontola** [comment]
> - capitalize menu (e.g. "CATALOGUE") and hilight active menu as in production lbr.csc.fi

This can be done with custom CSS:
```css
.nav-item {
    text-transform: uppercase;
}
```

The missing highlighting is a bug. Another CSS rule overwrites the highlight color.

**Comment by mmatthiesencsc** [comment]
Hi Esko, thanks for the quick feedback, good that some of the issues are easy to fix. Please comment also on hard to fix issues, we can then decide to live with them if necessary. I really would like to get this update into production. Martin

**Comment by luontola** [comment]
Application numbering is currently under development: #1133

The feature which will enable the privacy policy page is under development: #472

Redacting the application could be done by allowing the applicant to close draft applications. Currently only the handler can do that (and only for approved applications). The UI might need some adjustment, e.g. removing the comment field.

**Comment by Macroz** [comment]
The main idea with the ellipsis `...` is to show which buttons open more options i.e. something to input and which are direct actions. There are two conventions for this. Using `...` is the age old one for example from Windows and OS/X program menus whereas a triangle is from e.g. GitHub here. There is no clear right alternative here as I see it.

**Comment by Macroz** [comment]
Withdrawal from the applicant's part has been left out, because we think it causes difficulties for the flow and is definitely not in the MVP. For example, the handler of an application can spend a lot of time working on handling the application, but then it is suddenly withdrawn and perhaps never resent by the applicant. It is easier if applications can only be returned by the handler if they are found lacking in the review.

If this assumption is wrong then it's of course possible to enable applicant withdrawals, but I'd like to see the business case for it.

**Comment by Macroz** [comment]
Menu capitalization is done in https://github.com/CSCfi/rems/issues/1128

**Comment by Macroz** [comment]
Regarding not accepting the licenses, the user can simply close the application?

**Comment by mmatthiesencsc** [comment]
Hi, I guess we can live with the "...", I see the logic, I am still not sure I like the visuals, but I guess the standard is there. 
More importantly: Closing/discarding an unsent application: This is not possible, at least I did not see how.
To repeat: 
- Add an item to cart
- Click Apply
-> Error: You can only Save as Draft or Send the Application
-> Expected: an additional "Discard" option.
No disagreement with already sent applications, I agree that user withdrawal makes little sense, if the application has already been sent. In that case an email to us requesting a rejection is more than enough.

**Comment by Macroz** [comment]
@mmatthiesencsc you are right, the close/delete button is not shown at the moment for the applicant and it should be added there. Then I think this part is ok.

**Comment by mmatthiesencsc** [comment]
> @mmatthiesencsc you are right, the close/delete button is not shown at the moment for the applicant and it should be added there. 
Ok, that was what I meant.
>Then I think this part is ok.
Yes, no other additions needed there.

**Comment by Macroz** [comment]
I created this issue to track the close/delete https://github.com/CSCfi/rems/issues/1186

**Comment by Macroz** [comment]
I created #1188 for "Request decision without specified deciders"

**Comment by Macroz** [comment]
@foxlynx can you have a look at this?
> Bug:
https://lbr.csc.fi/#/application/809
shows up under "Open applications" after approval
Expected: Under processed applications

**Comment by foxlynx** [comment]
> @foxlynx can you have a look at this?
> 
> > Bug:
> > https://lbr.csc.fi/#/application/809
> > shows up under "Open applications" after approval
> > Expected: Under processed applications

#1191

**Comment by Macroz** [comment]
I updated the description of this issue to include links to all the created tasks and apparently only one is still to be done.

**Comment by hukka** [comment]
@mmatthiesencsc Do you think the issues mentioned here are now fixed, and this tracker is ready to be closed?

**Comment by mmatthiesencsc** [comment]
Yes, this is mostly fixed. One slight thing I wondered about: An open application can now be "Deleted", but only with A comment ("Not shown to applicant"). Is this something the end user sees, or is this due to my double role as user / admin? I would expect that the normal user Cancels the application (and also the admin, actually, before it has been sent.)
