### ISSUE TITLE
A11Y: Use HTML element roles

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#1212]
- [x] use `<h1>` as the top-level heading of each page; currently some pages use `<h2>` (#1247)
- [x] use HTML heading elements for all headings; currently form section headings are only divs (#1306)
- [x] use `<nav>` for the whole navigation menu; currently the sign out link is outside it (#1306)
  - `<nav role="navigation">` is redundant and can be removed
- [x] use `<main>` for the page content (#1259)

https://a11yproject.com/posts/aria-landmark-roles/

Required by 4.1.2 Name, Role, Value (Level A) https://www.w3.org/WAI/WCAG21/quickref/

Part of #1172
