### ISSUE TITLE
Approver bot

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#1660]
- [x] bot should not approve if user is on the blacklist for the resource (see #1682)
- [x] bot can be configured for a workflow (i.e. plugin for workflow, not new workflow type), maybe represented as a kind of handler
- [x] bots should not need to have an email (i.e. make email optional for non-human users)
- approve bot could cause a lot of spam so make the emails manageable, weekly summary mail to handlers? (split out to #1728)

**Comment by luontola** [comment]
The weekly summary email could be split into its own issue and put to ideas. Or just drop it and wait for feedback from production use.

**Comment by opqdonut** [comment]
First version of approver bot done, ready for testing IMO
