### ISSUE TITLE
Use Shadow-CLJS to build the front-end

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2755]
Using Shadow-CLJS to build the front-end would help use npm dependencies such as latest `react-select`.

We could keep Leiningen for the back-end / packaging.

This also means removing Figwheel (classic) as Shadow will replace it.

- [x] read and update docs (development.md, ...)
- [x] check circle build
- [x] make new release
- [x] decide between re-frisk and re-frame-10x (enabled re-frisk)
- [x] replace doo with shadow-cljs or kaocha (replaced with shadow-cljs + karma)
- [x] separate build for dev with less optimizations or at least source maps and pseudo names (can use `--debug`)

**Comment by Macroz** [comment]
We should finish this before any UI refresh.
