### ISSUE TITLE
Catalogue tree leftovers

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2800]
Continuation from #2796 and #2770.

- [x] bug: when an item is in multiple categories, filtering for it duplicates it more and more
- [ ] schema like in table
- [ ] share / re-use with table and implement refactorings and improvements to both (copypasta)
- [ ] owner can see disabled catalogue item in the tree (deeper than root level)
- [x] check performance of tree grouping in backend
- [x] check performance of rendering
- [ ] catalogue tree browser tests
- [x] admin UI browser tests #2802 
- [ ] refactor create catalogue item browser test to use admin UI and not test helpers
- [ ] animate opening and closing (could be difficult)
- [x] hide category if there are no items in it (yet) #2805 
- [x] the categories should be sortable by the admin to an optimal order and it should be respected while sorting #2808 
- [x] check that the category does not cause a loop when saving a category #2806 
- [x] description should show (optional) #2804 
- [ ] optional feature: count of items under a category (e.g. show "Ordinary (6)" as label)
- [ ] optional feature: show/hide category. return in API but don't show in catalogue if hidden (kind of like catalogue items).

**Comment by Macroz** [comment]
Performance is OK so far.
