### ISSUE TITLE
Localization improvements

### ISSUE THREAD

**Issue by aatkin** [CSCfi/rems#3241]
- [x] Add support for named parameters to email templates #3247
- [x] Remove format parameter tests and runtime checks #3247
- [x] Update `com.taoensso/tempura` dependency to latest #3247

Email template localizations use a relatively high number of shared variable parameters, up to 6, which are used via index numbers: `"%1 %2 %3 ..."`. Not every email localization uses every parameter, which makes it increasingly more difficult to maintain them. Named parameters support was added in #3183, and it allows incremental update from index parameters to named parameters: `"%:param-1% %:param-2% %:param-3% ..."`

Currently used parameters in email templates:

| index | new named parameter?  | description                                                   |
| --------------- | ---------------- | ------------------------------------------------------------- |
| %1              | %:recipient%       | name of recipient                                             |
| %2              | %:event-actor%     | name of event actor                                           |
| %3              | %:application-id%  | id of application (+ description of application if available) |
| %4              | %:applicant%       | name of applicant                                             |
| %5              | %:catalogue-items% | catalogue items of application, comma separated list          |
| %6              | %:application-url% | link to application                                           |

REMS has several checks regarding translations:
- Tests that all core localization keys are used in source code,
- Tests that format parameters are the same across all core translations,
- Runtime verification that extra translations replace existing localization keys, and
- Runtime verification that format parameters are the same for extra translation and core translation.

For backwards compatibility, translations that support named parameters also support index parameters. Parameter checking has been problematic before because of strict checking, and even more so with named parameters.
