### ISSUE TITLE
admin dashboard

### ISSUE THREAD

**Issue by ghost** [CSCfi/rems#369]
- [ ] add admin role
- [ ] dashboard route for admin role
- [ ] show all applications
- [ ] entitlement logs

**Comment by Macroz** [comment]
Reporter role is somewhat an admin role these days.

Entitlement push / outbox state could be useful.
