### ISSUE TITLE
vTHL2: Listing views of different REMS concepts in admin pages

### ISSUE THREAD

**Issue by cscwooller** [CSCfi/rems#805]
Bundled to one story, can be split.

## Catalogue items
- [x] listing exists but should be on its own page
- [x] show catalogue item creation date
- [x] show resource, form and workflow
- link to resource, form and workflow directly (in #866)

## Licenses
- [x] list of licences
- [x] show license name and creation date
- link to license attachment, url or popup showing text (in #866)

## Forms
- [x] list of forms
- [x] show form name and creation date
- link to detail view of form (in #866)
- copy action (or placeholder) (see #836)
- update action (or placeholder) (see #865)

## Workflows
- [x] list of workflows
- [x] show workflow title and creation date
- link to detail view of workflow (in #866)

## Resources
- [x] list of resources
- [x] show resource organization (i.e. domain), id and creation date

**Comment by Macroz** [comment]
Implemented in #885
