### ISSUE TITLE
vTHL2: Archiving resources, licences, workflows and forms   

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#806]
There should be a way to archive resources, workflows, forms and catalogue items (enable / disable exists for catalogue item already)

- [x] add state to all if there is not a column yet (keep start and end times also for other use)
- catalogue items
  - [x] add archive/unarchive action
  - [x] add "show archived" checkbox
  - [x] hide expired from applicants
  - [x] hide archived from applicants
  - disabled catalogue items already hidden from applicant, warning shown for drafts with disabled
- resources
  - [x] add enable/disable action
  - [x] add archive/unarchive action
  - [x]  add "show archived" checkbox
- forms
  - [x] add enable/disable action
  - [x] add archive/unarchive action
  - [x]  add "show archived" checkbox
- workflows
  - [x] add enable/disable action
  - [x] add archive/unarchive action
  - [x]  add "show archived" checkbox
- licenses
  - [x] add enable/disable action
  - [x] add archive/unarchive action
  - [x]  add "show archived" checkbox
- [x] item cannot be archived if it's part of some non-archived catalogue item
  - [x] better error messages (the conflicting items are not included in the UI error at the moment)
- [x] archived item (resource, WF, form) must not be selectable during catalogue item creation (filter autocomplete)
- [x] expired items (after end date) should also not be available anymore like archived
- [x] expired items should be hidden unless archived checkbox is selected
- [x] in progress applications: show warning about disabled, archived and expired items
- catalogue item, resource or workflow can not be unarchived if its parts are archived (split out to issue #1094)

**Comment by Macroz** [comment]
Blocked by #805

**Comment by luontola** [comment]
It was discussed that the database tables will need four columns: start (timestamp), end (timestamp), enabled (boolean), archived (boolean). On the user pages will be shown those with start<now<end & enabled=true & archived=false. On the admin pages will be shown all except archived which are hidden by default and can be shown at the click of a button/checkbox.

**Comment by opqdonut** [comment]
after discussion, decided to implement this so that:

- catalogue items, forms, resources, workflows and licenses can be enabled/disabled independently
- disabling a catalogue item means it can't be applied for
- disabling a form/resource/workflow/license means it can't be used when creating new catalogue items
- a form/resource/workflow/license can only be archived if the catalogue items using it are all archived

**Comment by luontola** [comment]
How shall expiring fit into this? After the expiry date, should the thing behave similar to disabled or archived or still a third way?

**Comment by opqdonut** [comment]
that's to be decided...

**Comment by opqdonut** [comment]
> It was discussed that the database tables will need four columns: start (timestamp), end (timestamp), enabled (boolean), archived (boolean). On the user pages will be shown those with start<now<end & enabled=true & archived=false. On the admin pages will be shown all except the archived things, which are hidden by default and can be shown at the click of a button/checkbox.

Editing the checklist since we don't have a "user page" for anything else than catalogue items

**Comment by opqdonut** [comment]
I just checked that archived/expired licenses/workflows/forms/resources are not selectable when creating a new catalogue-item/resource/workflow

**Comment by opqdonut** [comment]
all done!
