### ISSUE TITLE
test-data improvements

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#849]
- [ ] remove duplication between test-data and demo-data
- [ ] good demo data for THL use
- [ ] good demo data for rems2demo site
- [ ] good demo data for development and accepting issues
- [ ] don't rely on hard-coded test-data ids in e.g. api tests (create test data for each case in the test)
- [ ] use high-level APIs (preferably the public API) for creating the test data instead of using `rems.db.core` directly
- [ ] application with attachment license
- [ ] bundlable set of catalogue items

**Comment by opqdonut** [comment]
I think this is pretty much done now
