### ISSUE TITLE
vTHL3: Remove round-based workflow

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#852]
Background:

- dynamic workflow should be enough for everybody
- we want to get rid of old round-based workflow
  - db tables
  - `get-form-for`
- old application API conflates forms with applications
- we might need a new autoapprove workflow (if LBR needs it)

Steps:
- [x] spike for new application API (#878)
- [x] code for converting round-based applications to dynamic applications (for LBR production data) (TBD: how much granularity to preserve) (#948)
- [x] feature complete new application API (#1004, #1012)
- [x] decouple dynamic workflow from round-based workflow
  - [x] form validation (#1013)
  - [x] creating/saving the application (#1031)
- [x] replace `rems.workflow.dynamic/apply-event` multimethod with new `rems.api.applications-v2/application-view` (#1050 #1054 #1056 #1062 #1065)
  - the old tests must be run against the new implementation
  - or then follow CQRS: keep the old method as the write model and use the new method as the read model
- [x] switch to new application API in frontend (#1015, #1017)
- [x] applications page: use the new application API directly instead of through v2->v1 transformation (#1024)
- [x] remove old application API (#1020 #1021 #1022 #1033)
- [x] remove /api/v2/applications/:id/migration (#1063 #1066)
- [x] rename new v2 API to v1 or rename all the remaining ones to v2 (#1064 #1088)
- [x] remove dead code:
  - [x] remove `applicant`, `approver` and `reviewer` roles from database (#1036)
    - also cleanup `rems/roles.cljs` and lots of other code
    - consider renaming the `owner` role to `admin`
  - leftovers in #1101 
- [x] solve the cyclic dependency and `resolve` hack at https://github.com/CSCfi/rems/blob/39f75e287d7a33dc0f424e0c6bbc63a27b19fff1/src/clj/rems/db/applications.clj#L1033 (#1033)

**Comment by luontola** [comment]
Currently any further cleanup is blocked by the code which migrates old applications to dynamic workflow. After releasing a version of the application which can do the migration, the migration code can be removed and lots of dead code with it.

**Comment by opqdonut** [comment]
leftovers split out
