### ISSUE TITLE
vTHL4: Editors in admin pages

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#867]
Edit page for each concept in admin pages.

Simple cases:
- [ ] edit catalogue item (rename) (see #1507)

More complex:
- [ ] edit resource (change urn?, change licenses) (#1369)
- [x] edit workflow (rename, change handlers) (see #1103)
- [x] edit form (see #865 , #836)

Licence can't be renamed (@jaakkocsc 16.8.2019)

**Comment by okahilak** [comment]
One use case, from LBR's Martin:

"At the moment there is no way to edit a resource using the same ID. This is important to fix typos and similar issues.

Case in point:
https://lbr.csc.fi/#/administration/resources/50

The licence text is partly wrong (+LOC should not be there). I cannot fix this without creating a different resource under a different name. But his would break the whole logic behind the URN used, since the real resource has not changed.

Suggestion: Instead of making it impossible to edit resources, make them editable and track the changes."

**Comment by mmatthiesencsc** [comment]
Another real-life example: I added a licence and wrote (rather copy/pasted) the links as urn.fi/urn:nbn:.. (instead of http;//urn.fi/urn:nbn:..) The links did not work and I had the same problem as above, I fixed it by changing the database.

**Comment by foxlynx** [comment]
Invalidate cache for related items.

**Comment by opqdonut** [comment]
All work split into separate tickets

**Comment by mmatthiesencsc** [comment]
This was actually not done for Resources or Licences. Especially for resources this is a problem, since we use PID to refer to them and having to mint a new PID to fix a minor typo makes no sense. (But great that most other Admin items are now editable.)
